// <auto-generated />
using Labb3.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb3.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb3Models.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyId");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            HobbyId = 1,
                            Description = "Paint or draw artwork.",
                            Title = "Art"
                        },
                        new
                        {
                            HobbyId = 2,
                            Description = "Listen or/and create music.",
                            Title = "Music"
                        },
                        new
                        {
                            HobbyId = 3,
                            Description = "Code video games.",
                            Title = "Game Development"
                        },
                        new
                        {
                            HobbyId = 4,
                            Description = "Sculpt models with clay or software.",
                            Title = "Sculpting"
                        });
                });

            modelBuilder.Entity("Labb3Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("varchar(200)");

                    b.HasKey("LinkId");

                    b.HasIndex("HobbyId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            HobbyId = 1,
                            PersonId = 4,
                            URL = "wikiart.org/"
                        },
                        new
                        {
                            LinkId = 2,
                            HobbyId = 2,
                            PersonId = 3,
                            URL = "soundcloud.com/jerm-495708466"
                        },
                        new
                        {
                            LinkId = 3,
                            HobbyId = 3,
                            PersonId = 1,
                            URL = "unity.com/"
                        },
                        new
                        {
                            LinkId = 4,
                            HobbyId = 4,
                            PersonId = 5,
                            URL = "en.wikipedia.org/wiki/Sculpture"
                        },
                        new
                        {
                            LinkId = 5,
                            HobbyId = 3,
                            PersonId = 2,
                            URL = "unrealengine.com/en-US/"
                        });
                });

            modelBuilder.Entity("Labb3Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            FirstName = "Jeremy",
                            LastName = "Cedendahl",
                            PhoneNumber = "0702556191"
                        },
                        new
                        {
                            PersonId = 2,
                            FirstName = "Basse",
                            LastName = "Cedendahl",
                            PhoneNumber = "07012345678"
                        },
                        new
                        {
                            PersonId = 3,
                            FirstName = "Johan",
                            LastName = "Fältholm",
                            PhoneNumber = "07012335679"
                        },
                        new
                        {
                            PersonId = 4,
                            FirstName = "Anton",
                            LastName = "Olsson",
                            PhoneNumber = "07012349587"
                        },
                        new
                        {
                            PersonId = 5,
                            FirstName = "Carina",
                            LastName = "Cedendahl",
                            PhoneNumber = "073234232"
                        });
                });

            modelBuilder.Entity("Labb3Models.PersonHobby", b =>
                {
                    b.Property<int>("PersonHobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonHobbyId");

                    b.HasIndex("HobbyId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonHobbies");

                    b.HasData(
                        new
                        {
                            PersonHobbyId = 1,
                            HobbyId = 1,
                            PersonId = 4
                        },
                        new
                        {
                            PersonHobbyId = 2,
                            HobbyId = 2,
                            PersonId = 3
                        },
                        new
                        {
                            PersonHobbyId = 3,
                            HobbyId = 3,
                            PersonId = 1
                        },
                        new
                        {
                            PersonHobbyId = 4,
                            HobbyId = 4,
                            PersonId = 5
                        },
                        new
                        {
                            PersonHobbyId = 5,
                            HobbyId = 4,
                            PersonId = 2
                        },
                        new
                        {
                            PersonHobbyId = 6,
                            HobbyId = 3,
                            PersonId = 2
                        },
                        new
                        {
                            PersonHobbyId = 7,
                            HobbyId = 2,
                            PersonId = 1
                        });
                });

            modelBuilder.Entity("Labb3Models.Link", b =>
                {
                    b.HasOne("Labb3Models.Hobby", "Hobby")
                        .WithMany("Links")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb3Models.PersonHobby", b =>
                {
                    b.HasOne("Labb3Models.Hobby", "Hobby")
                        .WithMany("PersonHobbies")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3Models.Person", "Person")
                        .WithMany("PersonHobbies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
